#
# https://hub.docker.com/r/codercom/code-server/tags
#
ARG CS_VER=1.1156-vsc1.33.1
FROM codercom/code-server:${CS_VER}
USER root
RUN set -eux ; \
	apt-get update ; \
	apt-get install -y --no-install-recommends \
		ca-certificates tree jq software-properties-common curl gpg-agent cowsay; \
	rm -rf /var/lib/apt/lists/*
USER coder
RUN set -eux ; \
  code-server --install-extension cssho.vscode-svgviewer
ARG PATH_SETTINGS=/home/coder/.local/share/code-server/User/settings.json
RUN echo '\
{ \n\
  "rust-client.rustupPath": "/home/coder/.cargo/bin/rustup", \n\
  "rust-client.rlsPath": "/home/coder/.cargo/bin/rls", \n\
} \n\
' > ${PATH_SETTINGS} && cat ${PATH_SETTINGS}
