[book]
authors = ["y12studio"]
language = "zh-TW"
multilingual = false
src = "src"
title = "DLTDOJO3 第三新熵熱踢道場"

[output.html]
mathjax-support = true
additional-css = ["includes/css/taichu-raw.css"]


[output.html.playpen]
editable = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]