@startuml
header DLTDOJO
footer https://github.com/dltdojo/taichu-crypto
title mad-white-component-1907-1
skinparam handwritten false
left to right direction

package "Docker Container" {
    folder "Code Server container"{
      [Code\nServer] as CS #Yellow
      [mad-white\nprojects]
      folder "VS Code Extension"{
       [plantuml]
      }
    }
}

package "Kubernetes" {
  folder "microk8s" {
	[DNS]
	[Registry]
	[Storage]
  }
  folder "Gitops"{
    [GIT gogs] as GIT #Green
    [CI drone] as CI #Blue
  }
}

CS --> GIT : 1. push
GIT -> CI : 2. build and test
CI --> Registry : 3. push
CI <-- Registry : 4. pull image

@enduml
