# ┌-------------------┐
# ┆ requirement gogs  ┆
# └-------------------┘
# gogs
# https://github.com/helm/charts/tree/master/incubator/gogs
# https://github.com/helm/charts/blob/master/incubator/gogs/values.yaml
# https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md#overriding-values-of-a-child-chart
gogs:
  enabled: false
  service:
    httpNodePort: 30521
    sshNodePort: 30522
    gogs:
      serviceEnableCaptcha: false
  postgresql:
    persistence:
      enabled: false
# ┌--------------------┐
# ┆ requirement drone  ┆
# └--------------------┘
# https://github.com/helm/charts/tree/master/stable/drone
drone:
  enabled: false
  service:
    type: NodePort
    nodePort: 30531
  sourceControl:
    provider: gogs
    gogs:
      server: http://mad-white-1907-gogs.default.svc.cluster.local
# ┌----------------┐
# ┆ vault dev mode ┆
# └----------------┘
vault:
  enabled: true
  image:
    tag: 1.1.3
  replicaCount: 1
  service:
    type: NodePort
# ┌---------------------┐
# ┆ Local nginx service ┆
# └---------------------┘
nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: 1.17-alpine
  service:
    type: NodePort
    port: 8080
    targetPort: 80
    nodePort: 30520
  htmlDir: /usr/share/nginx/html
# ┌----------┐
# ┆ registry ┆
# └----------┘
registry:
  urlInK8s: registry.container-registry.svc.cluster.local:5000
  urlInHost: localhost:32000
# ┌--------┐
# ┆ kaniko ┆
# └--------┘
kaniko:
  # dnsPolicy: Default
  dnsPolicy: ClusterFirst
# ┌-----------------------┐
# ┆ jsonld.org playground ┆
# └-----------------------┘
jsonld:
  enabled: false
  image:
    name: mad-white-jsonld
    tag: 0.2.5
  service:
    type: NodePort
    port: 8081
    targetPort: 80
# ┌------------------------┐
# ┆ swagger-api/swagger-ui ┆
# └------------------------┘
swaggerUi:
  enabled: false
  image:
    name: mad-white-swapi
    tag: 0.0.1
  service:
    type: NodePort
    port: 8082
    targetPort: 80
# ┌-------------┐
# ┆ code server ┆
# └-------------┘
codeServer:
  enabled: false
  dir: /tmp
  image:
    name: mad-white-vscsrv
    tag: 0.1.1
  service:
    type: NodePort
    port: 8083
    targetPort: 8443
# ┌-----------------┐
# ┆ PlantUML server ┆
# └-----------------┘
plantUMLServer:
  enabled: false
  image:
    name: plantuml/plantuml-server
    tag: jetty
  service:
    type: NodePort
    port: 8084
    targetPort: 8080


