' https://hyperledger-fabric.readthedocs.io/en/release-1.4/developapps/scenario.html
' The PaperNet commercial paper network. Six organizations currently use PaperNet network to 
' issue, buy, sell, redeem and rate commercial paper. 
' MagentoCorp issues and redeems commercial paper. 
' DigiBank, BigFund, BrokerHouse and HedgeMatic all trade commercial paper with each other. 
' RateM provides various measures of risk for commercial paper.
'
@startuml

participant MagentoCorp #yellow
participant DigiBank
collections PaperNet #green
participant BigFund
participant BrokerHouse
participant HedgeMatic
participant RateM

== 100 PaperNet commercial paper network ==
MagentoCorp <-> PaperNet: issue/redeem
note right #aqua
  MagentoCorp issues and 
  redeems commercial paper. 
end note
DigiBank <-> PaperNet: buy/sell/redeem
note right
	DigiBank, BigFund, BrokerHouse and HedgeMatic 
    all trade commercial paper with each other. 
end note
BigFund <-> PaperNet: buy/sell/redeem
BrokerHouse <-> PaperNet: buy/sell/redeem
HedgeMatic <-> PaperNet: buy/sell/redeem
RateM <-> PaperNet: rate/notify
note left #red
	RateM provides various measures of risk 
    for commercial paper.
end note
@enduml