{{- if .Values.swaggerUi.enabled }}
---
apiVersion: v1
data:
  Dockerfile: |-
    FROM alpine as cloner
    RUN apk --update add curl unzip && \
      rm -rf /var/lib/apt/lists/* && \
      rm /var/cache/apk/*
    RUN mkdir -p /git/
    WORKDIR /git/
    ARG GIT_ZIP=https://github.com/swagger-api/swagger-ui/archive/master.zip
    ARG GIT_DIR=swagger-ui
    RUN curl -SL ${GIT_ZIP} -o /tmp/git.zip && \  
      unzip /tmp/git.zip -d . && mv ${GIT_DIR}-master/dist ${GIT_DIR}
    #
    # STAGE deployment
    # 
    FROM nginx:1.17-alpine
    ARG GIT_DIR=swagger-ui
    RUN rm -rf /usr/share/nginx/html
    COPY --from=cloner /git/${GIT_DIR} /usr/share/nginx/html
    RUN ls -al /usr/share/nginx/html
    CMD ["nginx", "-g", "daemon off;"]
kind: ConfigMap
metadata:
  name: dockerfile-swagger-ui
---
apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name}}-build-swagger-ui
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    volumeMounts:
    - name: dockerfile
      mountPath: /build/Dockerfile
      subPath: Dockerfile
    args:
    - --dockerfile=/build/Dockerfile
    - --destination={{ .Values.registry.urlInK8s}}/{{ .Values.swaggerUi.image.name }}:{{ .Values.swaggerUi.image.tag }}
    - --context=/build
    - --insecure
    - --verbosity=debug
  restartPolicy: Never
  dnsPolicy: {{ .Values.kaniko.dnsPolicy}}
  volumes:
  - configMap:
      name: dockerfile-swagger-ui
    name: dockerfile
{{- end }}